### ISSUE TITLE
Build a MapComplete studio

### ISSUE THREAD

**Issue by pietervdvn** [pietervdvn/MapComplete#1184]
One of the NLNet tasks is to create a MapComplete Studio

# Introduction

A theme can be created by defining a .json-file, which configures one such a thematic map. While
many contributors to MapComplete have made such a map, creating a .json-file is a hurdle that
frightens many non-programmers. A graphical environment would make it easier for someone with
a lot of OSM-experience to create and to contribute a map. Even though an old (and abandoned)
page exists, this workflow is buggy and a big barrier to entry, even for experienced
OpenStreetMappers.
An important target group of this functionality are municipalities. They often have (open) geodata,
but struggle to effectively communicate this data to their citizens and they struggle to keep this
data up to date. MapComplete could be the perfect solution to these problems. As such, I’d like to
convince at least one municipality to try this.

# Tasks

- [x] Set up a GUI which creates a (basic) .JSON-file that can be shared
- [x] Set up a way to easily share maps (and to contribute them back to MapComplete)
- [x] Usertest the flow with at least two experienced mapper (but who hasn’t made a MapComplete theme before), blog about the outcome
- [x] Document the new flow (in a blog/diary entry, possibly a talk on a conference)
- [x] Test the setup of a map for a municipality website

As this issue is mostly for project management, no discussions are allowed here. Use #173 for technical discussions, feature requests etc...
