### ISSUE TITLE
Add favourites

### ISSUE THREAD

**Issue by pietervdvn** [pietervdvn/MapComplete#1185]
One of the NLNet tasks is to give contributors the chance to add favourites

# Introduction

An important feature in many map applications is the possibility to add locations as favourites, in
order for people to quickly go to their favourite locations.

# Tasks

- [ ] Integrate buttons in the GUI a location as favourite
- [ ] Store favourites within the OSM-user-preferences
- [ ] Show favourites on the map, with basic information
- [ ] Add possibility to delete a favourite

As this issue is mostly for project management, no discussions are allowed here.

**Comment by pietervdvn** [comment]
![image](https://github.com/pietervdvn/MapComplete/assets/1466478/ac27b178-2f79-45a7-85b1-1a690f582f93)

![image](https://github.com/pietervdvn/MapComplete/assets/1466478/1548e92a-dac0-4da9-95fa-9fb37d55499a)

![image](https://github.com/pietervdvn/MapComplete/assets/1466478/12289776-3d30-486d-9322-c586256e29f7)
