### ISSUE TITLE
Velopark: intermediate todo

### ISSUE THREAD

**Issue by pietervdvn** [pietervdvn/MapComplete#1783]
(This ticket is for the commissioned velopark project)

- [x] Add text field in Maproulette-close-button to signal _what_ is wrong
- [x] MapRoulette buttons should be behind a login wall
- [x] Nearby check: also include contours? Centerpoint might be far away
- [x] Vergelijkend rapport genereren

Volgende versie: halverwege maart

**Comment by pietervdvn** [comment]
https://data.velopark.be/openvelopark/vocabulary
