### ISSUE TITLE
Move all the pictures from Imgur to Panoramax

### ISSUE THREAD

**Issue by pietervdvn** [pietervdvn/MapComplete#2189]
# Why move?

1. Even though imgur hosts the images for now, they might delete it whenever they feel like. They suddenly cutoff our possibility to upload too.
2. Imgur indicated that they do not want to be used as third parties "content delivery network", which is how we are using it
3. Loading an image from Imgur has a privacy implication
4. Some people do not want to interact with non FLOSS-services

Also see the discussion here: https://community.openstreetmap.org/t/imgur-is-going-to-delete-old-images/98229

# Why not keep the `image`-tags? Or why not replacing them with `image=https://panoramax.xyz/hash`?

I'm not keeping the old `image`-tags, because

- removing them later on will become harder
- everything is in a few changesets, which makes data maintainence easier
- applications supporting both will show duplicate images (which might prompt some people to remove the duplicate at random)

An option would be to include a panoramax-link instead. However, this duplicates data and is "tagging for the renderer". We don't use both `wikimedia=File:abc` and `image=https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/qsdfqsdf.jpg` either.

We are aware that this move breaks many existing applications and that this causes some friction. But, keep in mind that the picture that ""disappeared"" wouldn't have existed in the first place if it wasn't for mapcomplete. If you are a developer, [checkout the wiki on how to show those images too](https://wiki.openstreetmap.org/wiki/Panoramax#For_developers). If you are a user and see images missing in your favourite app, complain to the app maker.

# The image link got removed without panoramax alternative. Why?

If the image tag was removed from an object without replacement, then the image was dead and we did'nt have it in our own backups. This was especially the case for some 12 year old (!) links on objects in Germany.

# Todo

- [x] determine which tags might use imgur (e.g. streetsigns and menus)
- [x] Determine server to upload to (osm.fr or mc?)
- [x] Prepare technical process
- [x] Discuss mechanical edit with the community
- [x] include .png images in the upload

Note: there is no legal problem; everyone did give the rights to their picture as `CC0` or `CC-BY(-SA)`, so we can just grab them and move them without informing contributors. 

# Actual changes

Changesets where the images were moved:

- https://www.openstreetmap.org/changeset/158261875
- https://www.openstreetmap.org/changeset/158262040
- https://www.openstreetmap.org/changeset/158262099
- https://www.openstreetmap.org/changeset/158262456
- https://www.openstreetmap.org/changeset/158306608
- https://www.openstreetmap.org/changeset/158467174 (Flanders, reverted due to bug)
- https://www.openstreetmap.org/changeset/158468181 (Flanders, reverted due to bug)
- https://www.openstreetmap.org/changeset/158474093 (Flanders, *)
- https://www.openstreetmap.org/changeset/158477812 (Flanders, *)
- https://www.openstreetmap.org/changeset/158487373 (Flanders, *)
- https://www.openstreetmap.org/changeset/158953452 (Flanders)
- https://www.openstreetmap.org/changeset/158988074 (Barcelona)
- https://www.openstreetmap.org/changeset/159006999 (Spain + Portugal)
- https://www.openstreetmap.org/changeset/159060526 (France)
- https://www.openstreetmap.org/changeset/159060824 (Hong kong)
- https://www.openstreetmap.org/changeset/159061055 (Philippines)
- https://www.openstreetmap.org/changeset/159062096 (Italy, Slovenia, Balkan area, Greece, Romania)
- https://www.openstreetmap.org/changeset/159066767 (Chili)
- https://www.openstreetmap.org/changeset/159109786 (South America)
- https://www.openstreetmap.org/changeset/159112130 (UK, Ireland)
- https://www.openstreetmap.org/changeset/159150826 (Germany; first CS with autoremoval of dead images)
- https://www.openstreetmap.org/changeset/159223421 (Poland)
- https://www.openstreetmap.org/changeset/159226257 (Scandinavia + Baltics)
- https://www.openstreetmap.org/changeset/159226709 (Iceland)
- https://www.openstreetmap.org/changeset/159227140 (US, Mexico, Canada)
- https://www.openstreetmap.org/changeset/159227210 (Japan)
- https://www.openstreetmap.org/changeset/159227290 (Aotearoa)
- https://www.openstreetmap.org/changeset/159227329 (Australia)
- https://www.openstreetmap.org/changeset/159227492 (Jakarta)
- https://www.openstreetmap.org/changeset/159227532 (Canary Islands)
- https://www.openstreetmap.org/changeset/159227586 (Russia)
- https://www.openstreetmap.org/changeset/159227609 (Austria, Hungary, Romania; leftovers)
- https://www.openstreetmap.org/changeset/159227630 (India)
- https://www.openstreetmap.org/changeset/159227671 (Cyprus)
- https://www.openstreetmap.org/changeset/159227684 (Yemen)
- https://www.openstreetmap.org/changeset/159227702 (Vietnam) (Done with global BBox)
- https://www.openstreetmap.org/changeset/159250774 (PNG-images, worldwide)

The flanders changesets moved about 2.8% of existing `image`-tags.

*: the dates are not set correctly. Will be fixed in the future, see https://gitlab.com/panoramax/server/api/-/issues/207

More changes will follow

# Discussions and threads about the move:

- https://community.openstreetmap.org/t/usage-of-imgur-hosted-images/
- https://community.openstreetmap.org/t/defibrillators-imgur-verwijderen/120640
- https://community.openstreetmap.org/t/imgur-is-going-to-delete-old-images/98229 (older discussion)
- https://www.openstreetmap.org/changeset/15848737
- https://community.openstreetmap.org/t/moving-images-from-imgur-to-panoramax/120913

# Tools

[Overpass-turbo showing images from igmur](https://overpass-turbo.eu/s/1TVB)

**Comment by thibaultmol** [comment]
(I personally am going to manually replace all my images because then all the image EXIF data will be on panoramax and the location and such will be correct. but I know that's not viable for most others)

**Comment by pietervdvn** [comment]
All images with a license (thus including all mapcomplete-created images) are moved
