### ISSUE TITLE
Demoday Todo

### ISSUE THREAD

**Issue by pietervdvn** [pietervdvn/MapComplete#990]
- [x] add government layer --> Alexander
- [x] indoors layer --> Alexander
- [x] Check doors: old icon? --> Alexander
- [x] Add level question to all objects --> Alexander
- [x] disable some layers --> Andrews
- [x] set start location to herman teirlinck building --> ANdrews
- [x] Are all relevant questions on all icons their? Check the word-document -> Hassan
- [x] implement the dashboard --> Pietervdvn
- [x] levels switching --> Pietervdvn
- [x] merge all branches!  -> Pietervdvn
- [x] Fix dashboard --> Pietervdvn
- [x] Documentation -> Robin

**Comment by AlexanderRebai** [comment]
more to-do: 
[ ] Still need to fix the level question for elevators
[ ] Change the color of the indoor mappings
[ ] Hide doors until you zoom in to a certain level
